# Generated by Django 4.2 on 2023-05-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=30)),
                ('car_description', models.TextField()),
                ('car_notes', models.CharField(max_length=100)),
                ('car_owner', models.CharField(max_length=100)),
                ('service_type', models.CharField(blank=True, choices=[('E', 'Executive'), ('R', 'Regular')], max_length=1)),
                ('submission_date', models.DateTimeField()),
                ('servicing', models.ManyToManyField(blank=True, to='carapp.service')),
            ],
        ),
    ]
