# Generated by Django 4.2 on 2023-05-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='servicing_cost',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
