# Generated by Django 4.2 on 2023-05-10 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_car_servicing_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
