# Generated by Django 4.2 on 2023-05-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_alter_car_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='service_type',
            field=models.CharField(blank=True, choices=[('CW', 'Car Wash'), ('CS', 'Car Service')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='car',
            name='servicing',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='car',
            name='servicing',
            field=models.CharField(blank=True, choices=[('PL', 'Polishing'), ('BF', 'Buffing'), ('EW', 'Engine Wash'), ('UW', 'Under Wash')], max_length=2),
        ),
    ]
