# Generated by Django 4.2 on 2023-05-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_alter_car_service_type_remove_car_servicing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_notes',
            field=models.TextField(),
        ),
    ]
