# Generated by Django 4.2 on 2023-05-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_alter_car_car_description_alter_car_car_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_owner',
            new_name='car_owner_name',
        ),
        migrations.AddField(
            model_name='car',
            name='car_owner_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
