# Generated by Django 4.2 on 2023-05-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_rename_car_owner_car_car_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Car Wash', 'Car Wash'), ('Car Service', 'Car Service')], default='Car Wash', max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='servicing',
            field=models.CharField(blank=True, choices=[('Polishing', 'Polishing'), ('Buffing', 'Buffing'), ('Engine Wash', 'Engine Wash'), ('Under Wash', 'Under Wash')], max_length=15),
        ),
    ]
