# Generated by Django 4.2 on 2023-05-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0007_alter_car_service_type_alter_car_servicing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='servicing_cost',
            field=models.IntegerField(null=True),
        ),
    ]
