# Generated by Django 4.2 on 2023-05-30 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0008_alter_car_servicing_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groc_sales_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('groc_daily_sales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_sales_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rest_daily_sales', models.IntegerField()),
            ],
        ),
    ]
