# Generated by Django 4.2 on 2023-05-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0009_grocery_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='groc_daily_sales',
            field=models.CharField(max_length=10),
        ),
    ]
