# Generated by Django 4.2 on 2023-06-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0013_alter_car_submission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_commission', models.IntegerField()),
                ('misc_expenses', models.IntegerField(null=True)),
            ],
        ),
    ]
