# Generated by Django 4.2 on 2023-06-21 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0015_expenses_electricity'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='expenditure_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
