# Generated by Django 4.2 on 2023-06-21 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0017_alter_car_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 12, 6, 4, 52497, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expenditure_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 12, 6, 4, 54690, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='groc_sales_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 12, 6, 4, 53941, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rest_sales_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 12, 6, 4, 53366, tzinfo=datetime.timezone.utc)),
        ),
    ]
