# Generated by Django 4.2 on 2023-06-23 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0023_expenses_rent_alter_car_submission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_expenditure_date', models.DateField(default=datetime.datetime(2023, 6, 23, 0, 0))),
                ('g_salary_expenses', models.IntegerField(null=True)),
                ('g_misc_expenses', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_expenditure_date', models.DateField(default=datetime.datetime(2023, 6, 23, 0, 0))),
                ('r_salary_expenses', models.IntegerField(null=True)),
                ('r_misc_expenses', models.IntegerField(null=True)),
            ],
        ),
    ]
