# Generated by Django 4.2 on 2023-06-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0024_groceryexpense_restaurantexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='groc_daily_expenses',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='groc_net_sales',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rest_daily_expenses',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rest_net_sales',
        ),
    ]
