# Generated by Django 4.2 on 2023-06-25 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0025_remove_grocery_groc_daily_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 0, 0)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expenditure_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 0, 0)),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='groc_sales_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 0, 0)),
        ),
        migrations.AlterField(
            model_name='groceryexpense',
            name='g_expenditure_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 0, 0)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rest_sales_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 0, 0)),
        ),
        migrations.AlterField(
            model_name='restaurantexpense',
            name='r_expenditure_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 0, 0)),
        ),
    ]
